USE project;

# Add Primary Key
ALTER TABLE book_author
    ADD CONSTRAINT PRIMARY KEY (book_id, author_id);
ALTER TABLE carts
    ADD (CONSTRAINT PRIMARY KEY (book_id, user_id));
ALTER TABLE orderdetails
    ADD (CONSTRAINT PRIMARY KEY (order_id, book_id));

# Add Foreign Key
ALTER TABLE books
    ADD CONSTRAINT FOREIGN KEY (category_id) REFERENCES categories (category_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE books
    ADD CONSTRAINT FOREIGN KEY (publisher_id) REFERENCES publishers (publisher_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE users
    ADD CONSTRAINT FOREIGN KEY (reports_to) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE book_author
    ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES books (book_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE book_author
    ADD CONSTRAINT FOREIGN KEY (author_id) REFERENCES authors (author_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE carts
    ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES books (book_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE carts
    ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE reviews
    ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE reviews
    ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES books (book_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE orders
    ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE orders
    ADD CONSTRAINT FOREIGN KEY (coupon_id) REFERENCES coupons (coupon_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE orderdetails
    ADD CONSTRAINT FOREIGN KEY (order_id) REFERENCES orders (order_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE orderdetails
    ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES books (book_id) ON UPDATE CASCADE ON DELETE RESTRICT;